language: java

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

stages:
  - name: build
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      before_install:
        git checkout ${TRAVIS_BRANCH} # to fix travis checking out HEAD branch (breaks grgit)
      install: ./gradlew assemble
      script: ./gradlew check
    - stage: release
      script: ./gradlew publish -Ddisablesnapshot=true -Dnexus.user=$NEXUS_USER -Dnexus.key=$NEXUS_KEY
        -Dbuild.number=$TRAVIS_BUILD_NUMBER

deploy:
  provider: releases
  api_key:
    secure: A8JANJAzvBevIZD9F/J23iiRhBsRUKwi1YdKhstTP9WwsMUl6aM3NFwBQCV4bWSpRwNfvYAzUsRJVnqt2PyoSoVTnFIeXcCNQi6tiQBuakSfvNRueKlc4dLwENxBHhz1WvUui0oJocmAGDwmbjcPhtl/z5MDZpBZbL+X0JTym1Orza/BvaQhBFXI7w8lQG3okgoBXtB4B/yJV19m/X019fqDUnn1Vttxw+8ezVgwJmHTxyr/Jr65H9pwW3XtwfOJ2XvnJFKALpQDNZj6D2uLMZOT9Hljc6fvrQIYYbNJ4foJ46MlVBUDt7aq2Y3FwnM4hAwT1feJYrIOKq2mR0mzDGDsBwdTSDqnnCI06vpkqG0iBF5JtARU76BW5V40iZ98A2NvqH0Sg7qCtgU19n8VFjaTvD0g/bhe4PIsRkeFNKA5YySj1khAkUOXjfxn+BTtAAxQQDSp3rLw/k7o2pYyLzPMNiyKUgaQv6pRGBnJi5if6ujimKmC9c2UuYQF9S5HcOi5an+/vTY4/s1RmxKLthfBE5QJbTGggOEUYqWDFPSvReo7976FI3kodzMN0Fzu+Ib9zyzrKEEgXD5Dg4oFYA+7oWnaAGVLq7fiejssA96oZa7Hb6ODfmHl6XzoV6AmOT2/SlXstgj4CczJgp5D8cyLcRQP5DaO0UhbEY2Euvc=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: upbcuk/upb.crypto.math
    branch: release
