name: Main Java CI

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew :build -Prelease
  android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew android-test:connectedAndroidTest -Prelease -Pandroid.useAndroidX=true --info
