name: Scheduled Release Java CI

on:
  # Nightly builds to ensure dependencies don't break anything
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main # need to specify branch else it will check out develop
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew :build -Prelease
  android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew android-test:connectedAndroidTest -Prelease -Pandroid.useAndroidX=true --info